language: rust
os:
  - linux
  - osx
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: stable
notifications:
  email: false
before_script:
  - |
      if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
        cargo install clippy --force;
      fi
  - export PATH=$PATH:~/.cargo/bin
script:
  - cargo build --verbose
  - cargo test --verbose
  - |
      if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
        cargo clippy -- --deny warnings;
      fi
after_success:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_RUST_VERSION" == "nightly" && "$TRAVIS_PULL_REQUEST" = "false" && "$TRAVIS_BRANCH" == "master" ]]; then
        cargo doc &&
        echo "<meta http-equiv=refresh content=0;url=rsx/index.html>" > target/doc/index.html &&
        git clone https://github.com/davisp/ghp-import.git &&
        ./ghp-import/ghp_import.py -n -p -f -m "Documentation upload" -r https://"$GH_TOKEN"@github.com/"$TRAVIS_REPO_SLUG.git" target/doc &&
        echo "Uploaded documentation"
      fi
